// frontend_client/src/app/dashboard/reports/page.tsx
"use client";
import React, { useEffect, useState } from "react";
import {
  Box, Paper, Typography, FormControl, InputLabel, Select, MenuItem,
  Table, TableHead, TableRow, TableCell, TableBody, Button
} from "@mui/material";
import PrintIcon from "@mui/icons-material/Print";
import DownloadIcon from "@mui/icons-material/Download";
import { fetchProducts, fetchOperations, calculateMCT } from "../../../utils/api";
import { useAuth } from "../../../context/AuthContext";
import RequireAuth from "../../../components/RequireAuth";
import type { Product, Operation } from "../../../types";

function exportTableToCSV(tableId: string, filename: string) {
  const table = document.getElementById(tableId);
  if (!table) return;
  let csv: string = "";
  const rows = table.getElementsByTagName("tr");
  for (let i = 0; i < rows.length; i++) {
    const cols = rows[i].querySelectorAll("td,th");
    const row: string[] = [];
    for (let j = 0; j < cols.length; j++) {
      row.push('"' + cols[j].textContent?.replace(/"/g, '""') + '"');
    }
    csv += row.join(",") + "\n";
  }
  const blob = new Blob([csv], { type: "text/csv" });
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  window.URL.revokeObjectURL(url);
}

type MCTResult = { total_mct: number };

export default function ReportsPage() {
  const { token } = useAuth();
  const [products, setProducts] = useState<Product[]>([]);
  const [selectedProduct, setSelectedProduct] = useState<string>("");
  const [operations, setOperations] = useState<Operation[]>([]);
  const [mctResult, setMctResult] = useState<MCTResult | null>(null);

  useEffect(() => {
    (async () => {
      if (!token) return;
      const prods = await fetchProducts(token);
      setProducts(prods);
      if (prods.length) setSelectedProduct(prods[0].id.toString());
    })();
  }, [token]);

  useEffect(() => {
    (async () => {
      if (!token || !selectedProduct) return;
      setOperations(await fetchOperations(token, Number(selectedProduct)));
      setMctResult(await calculateMCT(token, Number(selectedProduct)));
    })();
  }, [token, selectedProduct]);

  return (
    <RequireAuth>
      <Box>
        <Typography variant="h4" color="primary.main" fontWeight={700} mb={2}>
          MCT Report
        </Typography>
        <Paper sx={{ mb: 2, p: 2, display: "flex", alignItems: "center", gap: 2 }}>
          <FormControl sx={{ minWidth: 200 }}>
            <InputLabel>Product</InputLabel>
            <Select
              label="Product"
              value={selectedProduct}
              onChange={(e) => setSelectedProduct(e.target.value)}
            >
              {products.map((p) => (
                <MenuItem key={p.id} value={p.id}>
                  {p.name}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          <Button
            startIcon={<PrintIcon />}
            color="primary"
            variant="outlined"
            onClick={() => window.print()}
            sx={{ ml: 1 }}
          >
            Print
          </Button>
          <Button
            startIcon={<DownloadIcon />}
            color="secondary"
            variant="outlined"
            onClick={() => exportTableToCSV("mct-table", "mct_report.csv")}
            sx={{ ml: 1 }}
          >
            Export CSV
          </Button>
        </Paper>
        <Paper sx={{ p: 3 }}>
          {mctResult && (
            <Box mb={2}>
              <Typography fontWeight={600}>
                Total MCT: <span style={{ color: "#f95801" }}>{mctResult.total_mct}</span> hours
              </Typography>
              <Typography variant="body2" color="secondary">
                ({products.find((p) => p.id === Number(selectedProduct))?.name || ""})
              </Typography>
            </Box>
          )}
          <Table id="mct-table">
            <TableHead>
              <TableRow>
                <TableCell>Step</TableCell>
                <TableCell>Operation</TableCell>
                <TableCell>MCT Time (hours)</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {operations.map((op) => (
                <TableRow key={op.id}>
                  <TableCell>{op.step_number}</TableCell>
                  <TableCell>{op.name}</TableCell>
                  <TableCell>{op.mct_time}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
          {!operations.length && (
            <Typography color="accent.main" p={2}>
              No operations for selected product.
            </Typography>
          )}
        </Paper>
      </Box>
    </RequireAuth>
  );
}

// frontend_client/src/routes/dashboard/reports/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { auth } from '$stores/auth';
  import {
    fetchProducts,
    fetchOperations,
    calculateMCT,
    Product,
    Operation
  } from '$api/rest';

  let products: Product[] = [];
  let selectedProduct = '';
  let operations: Operation[] = [];
  let mctResult: { total_mct: number } | null = null;

  $: token = $auth.token;

  async function getProducts() {
    if (!token) return;
    products = await fetchProducts(token);
    if (products.length) selectedProduct = products[0].id + '';
  }

  async function getReportData() {
    if (!token || !selectedProduct) return;
    operations = await fetchOperations(token, Number(selectedProduct));
    mctResult = await calculateMCT(token, Number(selectedProduct));
  }

  function exportTableToCSV(tableId: string, filename: string) {
    const table = document.getElementById(tableId);
    if (!table) return;
    let csv = '';
    const rows = table.getElementsByTagName('tr');
    for (let i = 0; i < rows.length; i++) {
      const cols = rows[i].querySelectorAll('td,th');
      const row: string[] = [];
      for (let j = 0; j < cols.length; j++) {
        row.push('"' + (cols[j].textContent ?? '').replace(/"/g, '""') + '"');
      }
      csv += row.join(',') + '\n';
    }
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    window.URL.revokeObjectURL(url);
  }

  function handlePrint() {
    window.print();
  }

  onMount(async () => {
    await getProducts();
  });
  $: if (token && selectedProduct) getReportData();
</script>

<h1 class="text-2xl font-bold text-primary mb-3">MCT Report</h1>
<div class="card p-3 flex flex-wrap items-center gap-3 mb-2">
  <select class="border rounded p-2 min-w-[180px]" bind:value={selectedProduct}>
    {#each products as p}
      <option value={p.id}>{p.name}</option>
    {/each}
  </select>
  <button
    class="px-4 py-2 border rounded border-primary text-primary font-medium hover:bg-gray-50"
    on:click={handlePrint}>Print</button>
  <button
    class="px-4 py-2 border rounded border-secondary text-secondary font-medium hover:bg-orange-50"
    on:click={() => exportTableToCSV('mct-table', 'mct_report.csv')}>Export CSV</button>
</div>
<div class="card p-4">
  {#if mctResult}
    <div class="mb-2 font-semibold">
      Total MCT: <span class="text-secondary">{mctResult.total_mct}</span> hours
    </div>
    <div class="text-sm text-accent mb-4">
      ({products.find(p => p.id + '' === selectedProduct)?.name || ''})
    </div>
  {/if}
  <table class="w-full text-left" id="mct-table">
    <thead class="border-b">
      <tr>
        <th class="py-2">Step</th>
        <th>Operation</th>
        <th>MCT Time (hours)</th>
      </tr>
    </thead>
    <tbody>
      {#each operations as op}
        <tr>
          <td class="py-1">{op.step_number}</td>
          <td>{op.name}</td>
          <td>{op.mct_time}</td>
        </tr>
      {/each}
    </tbody>
  </table>
  {#if operations.length === 0}
    <div class="text-accent p-2">No operations for selected product.</div>
  {/if}
</div>
