// frontend_client/src/components/SideNav.vue
<template>
  <v-navigation-drawer app permanent width="240" color="white" class="elevation-2">
    <v-list>
      <v-list-item>
        <v-list-item-title class="text-h5 font-weight-bold py-2 text-primary">
          MCT Calculator
        </v-list-item-title>
      </v-list-item>
      <v-divider></v-divider>
      <v-list-item link to="/dashboard">
        <v-list-item-icon><span class="material-icons">dashboard</span></v-list-item-icon>
        <v-list-item-title>Dashboard</v-list-item-title>
      </v-list-item>
      <v-list-item link to="/dashboard/products">
        <v-list-item-icon><span class="material-icons">list_alt</span></v-list-item-icon>
        <v-list-item-title>Products</v-list-item-title>
      </v-list-item>
      <v-list-item link to="/dashboard/operations">
        <v-list-item-icon><span class="material-icons">assignment</span></v-list-item-icon>
        <v-list-item-title>Operations</v-list-item-title>
      </v-list-item>
      <v-list-item link to="/dashboard/reports">
        <v-list-item-icon><span class="material-icons">assessment</span></v-list-item-icon>
        <v-list-item-title>Reports</v-list-item-title>
      </v-list-item>
      <v-divider class="my-2"></v-divider>
      <v-list-item @click="logout">
        <v-list-item-icon><span class="material-icons text-secondary">logout</span></v-list-item-icon>
        <v-list-item-title class="text-secondary">Logout</v-list-item-title>
      </v-list-item>
    </v-list>
  </v-navigation-drawer>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { useStore } from 'vuex';
import { useRouter } from 'vue-router';

export default defineComponent({
  setup() {
    const store = useStore();
    const router = useRouter();
    function logout() {
      store.dispatch('logout');
      router.push('/login');
    }
    return { logout };
  }
});
</script>

// frontend_client/src/components/SideNav.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { auth } from '$stores/auth';
  import { page } from '$app/stores';

  function nav(route: string) {
    goto(route);
  }

  function handleLogout() {
    auth.logout();
    goto('/login');
  }
</script>
<nav class="flex flex-col h-full bg-white border-r border-gray-200 w-56 min-h-screen">
  <div class="h-16 flex items-center justify-center text-xl text-primary font-bold border-b border-gray-100">
    MCT Calculator
  </div>
  <ul class="flex-1 pt-4">
    <li><button class="w-full text-left px-6 py-3 hover:bg-gray-100 flex items-center gap-2" on:click={() => nav('/dashboard')}>
      <span class="material-icons">dashboard</span>Dashboard</button>
    </li>
    <li><button class="w-full text-left px-6 py-3 hover:bg-gray-100 flex items-center gap-2" on:click={() => nav('/dashboard/products')}>
      <span class="material-icons">list_alt</span>Products</button>
    </li>
    <li><button class="w-full text-left px-6 py-3 hover:bg-gray-100 flex items-center gap-2" on:click={() => nav('/dashboard/operations')}>
      <span class="material-icons">assignment</span>Operations</button>
    </li>
    <li><button class="w-full text-left px-6 py-3 hover:bg-gray-100 flex items-center gap-2" on:click={() => nav('/dashboard/reports')}>
      <span class="material-icons">assessment</span>Reports</button>
    </li>
  </ul>
  <button class="p-4 w-full text-left bg-gray-50 hover:bg-gray-100 border-t border-gray-200 text-red-600" on:click={handleLogout}>
    <span class="material-icons align-middle mr-2">logout</span>Logout
  </button>
</nav>
<style>
  .material-icons {
    font-family: 'Material Icons', Arial, sans-serif;
    font-size: 1.4em;
    vertical-align: middle;
  }
</style>
