// frontend_client/src/components/TopBar.svelte
<script lang="ts">
  import { auth } from '$stores/auth';
  import { derived } from 'svelte/store';

  const userStore = derived(auth, $auth => $auth.user);
</script>

<header class="h-16 flex items-center px-6 justify-between bg-white border-b border-gray-200 w-full">
  <div class="font-bold text-primary text-lg">MCT Calculator</div>
  <div class="flex items-center gap-3">
    {#if $userStore}
      <span class="text-accent mr-2">{ $userStore.email }</span>
    {/if}
    <button class="border border-secondary px-3 py-1 rounded-2xl text-secondary hover:bg-orange-100" on:click={() => auth.logout()}>
      Logout
    </button>
  </div>
</header>

// frontend_client/src/components/TopBar.vue
<template>
  <v-app-bar app flat color="white" class="elevation-1">
    <v-toolbar-title class="text-primary font-weight-bold">MCT Calculator</v-toolbar-title>
    <div class="flex-grow-1"></div>
    <div v-if="user" class="d-flex align-center text-accent mr-3">{{ user.email }}</div>
    <v-btn color="secondary" variant="outlined" @click="logout">Logout</v-btn>
  </v-app-bar>
</template>

<script lang="ts">
import { defineComponent, computed } from 'vue';
import { useStore } from 'vuex';
import { useRouter } from 'vue-router';

export default defineComponent({
  setup() {
    const store = useStore();
    const router = useRouter();
    const user = computed(() => store.state.user);

    function logout() {
      store.dispatch('logout');
      router.push('/login');
    }

    return { user, logout };
  }
});
</script>
