// frontend_client/src/app/dashboard/page.tsx
"use client";
import { Box, Typography, Paper, Button, Stack } from "@mui/material";
import { useEffect, useState } from "react";
import { fetchProducts, calculateMCT } from "../../utils/api";
import { useAuth } from "../../context/AuthContext";
import RequireAuth from "../../components/RequireAuth";
import type { Product } from "../../types";

type MCTResult = { total_mct: number };

export default function DashboardHome() {
  const { token } = useAuth();
  const [products, setProducts] = useState<Product[]>([]);
  const [mctResults, setMctResults] = useState<MCTResult[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    (async () => {
      if (!token) return;
      const prods = await fetchProducts(token);
      setProducts(prods);
      if (prods.length) {
        setLoading(true);
        const results = await Promise.all(
          prods.map((product: Product) => calculateMCT(token, product.id))
        );
        setMctResults(results);
        setLoading(false);
      }
    })();
  }, [token]);

  return (
    <RequireAuth>
      <Box>
        <Typography variant="h4" fontWeight={700} mt={2} mb={2} color="primary.main">
          Dashboard
        </Typography>
        <Stack gap={3} direction={{ xs: "column", md: "row" }}>
          {products.map((p, idx) => (
            <Paper
              elevation={2}
              key={p.id}
              sx={{ flex: 1, p: 3, minWidth: 260, borderLeft: "6px solid #f95801" }}
            >
              <Typography variant="h6" fontWeight={600}>
                {p.name}
              </Typography>
              <Typography variant="body2" gutterBottom>
                {p.description}
              </Typography>
              <Typography fontWeight={500} mt={1}>
                MCT:{" "}
                <span style={{ color: "#f95801", fontWeight: 700 }}>
                  {loading ? "Calculating..." : mctResults[idx]?.total_mct ?? "--"}
                </span>{" "}
                hours
              </Typography>
              <Button
                color="secondary"
                variant="text"
                onClick={() => window.location.assign(`/dashboard/reports?product_id=${p.id}`)}
                sx={{ mt: 2 }}
              >
                View Report
              </Button>
            </Paper>
          ))}
          {!products.length && (
            <Paper elevation={1} sx={{ py: 6, px: 4, textAlign: "center", borderRadius: 2 }}>
              <Typography color="accent.main" fontWeight={500}>
                No products yet.
              </Typography>
              <Typography>Create a product to get started!</Typography>
            </Paper>
          )}
        </Stack>
      </Box>
    </RequireAuth>
  );
}

// frontend_client/src/routes/dashboard/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { auth } from '$stores/auth';
  import { fetchProducts, calculateMCT, Product } from '$api/rest';

  let products: Product[] = [];
  let mctResults: { total_mct: number }[] = [];
  let loading = false;

  $: token = $auth.token;

  onMount(async () => {
    if (!token) return;
    products = await fetchProducts(token);
    if (products.length) {
      loading = true;
      mctResults = await Promise.all(
        products.map(prod => calculateMCT(token, prod.id))
      );
      loading = false;
    }
  });
</script>

<h1 class="text-3xl font-bold mb-4 text-primary">Dashboard</h1>
<div class="flex flex-wrap gap-5">
  {#each products as p, idx}
    <div class="card border-l-4 border-secondary flex flex-col flex-grow min-w-[250px] p-5">
      <div class="font-semibold text-lg">{p.name}</div>
      <div class="text-accent text-sm">{p.description}</div>
      <div class="mt-2 font-semibold">
        MCT:
        <span class="text-secondary font-bold">
          {loading ? 'Calculating...' : mctResults[idx]?.total_mct ?? '--'}
        </span>
        hours
      </div>
      <button
        class="text-secondary underline mt-3 font-medium text-sm"
        type="button"
        on:click={() => window.location.assign(`/dashboard/reports?product_id=${p.id}`)}
      >
        View Report
      </button>
    </div>
  {/each}
  {#if products.length === 0}
    <div class="card p-5 text-center w-full">
      <div class="text-accent">No products yet.</div>
      <div>Create a product to get started!</div>
    </div>
  {/if}
</div>
